name: Generate ASCII Artwork

on:
  push:

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay Program
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "run for dragon" > dragon.txt

      - name: Upload dragon text file
        uses: actions/upload-artifact@v3
        with:
          name: dragon-text-file
          path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file

      - name: Test file exists and contains word
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file

      - name: Read file
        run: cat dragon.txt
